/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistemabiblioteca.GUI;

import com.mycompany.sistemaBiblioteca.Logica.Socio;

/**
 *
 * @author saave
 */
public class FrmHistorialSocio extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmHistorialSocio
     */
    public FrmHistorialSocio() {
        initComponents();
        llenarSocios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbSocio = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblTotalPrestamos = new javax.swing.JLabel();
        lblPrestamosActivos = new javax.swing.JLabel();
        lblMultasPendientes = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Seleccione Socio");

        cbSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(105, 105, 105)
                .addComponent(cbSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Libro", "Fecha Prestamo", "Fecha Prevista", "Fecha Devuelto", "Estado", "Multa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHistorial);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        lblTotalPrestamos.setText("Total Prestamos Historicos: 0");

        lblPrestamosActivos.setText("\"Préstamos Activos (Vigentes): 0");

        lblMultasPendientes.setText("Multas Totales Cobradas: $0.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotalPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrestamosActivos, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(lblMultasPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTotalPrestamos)
                .addGap(18, 18, 18)
                .addComponent(lblPrestamosActivos)
                .addGap(18, 18, 18)
                .addComponent(lblMultasPendientes)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 286, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSocioActionPerformed
        cargarHistorialSocio();
    }//GEN-LAST:event_cbSocioActionPerformed

    private final java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd");

    private void llenarSocios() {
        cbSocio.removeAllItems();
        java.util.ArrayList<com.mycompany.sistemaBiblioteca.Logica.Socio> lista
                = com.mycompany.sistemaBiblioteca.Logica.BibliotecaFacade.getInstancia().listarSocios();
        for (com.mycompany.sistemaBiblioteca.Logica.Socio s : lista) {
            cbSocio.addItem(s);
        }
        if (cbSocio.getItemCount() > 0) {
            cbSocio.setSelectedIndex(0);
        }
    }

    private void cargarHistorialSocio() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblHistorial.getModel();
        model.setRowCount(0);

        com.mycompany.sistemaBiblioteca.Logica.Socio s = (com.mycompany.sistemaBiblioteca.Logica.Socio) cbSocio.getSelectedItem();
        if (s == null) {
            return;
        }

        java.util.ArrayList<com.mycompany.sistemaBiblioteca.Logica.Prestamo> prestamos
                = com.mycompany.sistemaBiblioteca.Logica.BibliotecaFacade.getInstancia().listarPrestamos();

        int total = 0;
        int activos = 0;
        double multas = 0.0;

        for (com.mycompany.sistemaBiblioteca.Logica.Prestamo p : prestamos) {
            if (p.getSocio().getIdSocio().equals(s.getIdSocio())) {
                total++;
                if ("Activo".equalsIgnoreCase(p.getEstado())) {
                    activos++;
                }
                multas += p.getMulta() != null ? p.getMulta() : 0.0;

                Object[] fila = {
                    p.getIdPrestamo(),
                    p.getLibro().getTitulo(),
                    dateFormat.format(p.getFechaPrestamo()),
                    dateFormat.format(p.getFechaDevolucionPrevista()),
                    p.getFechaDevolucionReal() != null ? dateFormat.format(p.getFechaDevolucionReal()) : "-",
                    p.getEstado(),
                    p.getMulta() != null ? "$" + p.getMulta() : "$0.0"
                };
                model.addRow(fila);
            }
        }

        lblTotalPrestamos.setText("Total Préstamos Históricos: " + total);
        lblPrestamosActivos.setText("Préstamos Activos (Vigentes): " + activos);
        lblMultasPendientes.setText("Multas Totales Cobradas: $" + multas);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Socio> cbSocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMultasPendientes;
    private javax.swing.JLabel lblPrestamosActivos;
    private javax.swing.JLabel lblTotalPrestamos;
    private javax.swing.JTable tblHistorial;
    // End of variables declaration//GEN-END:variables
}
