/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistemabiblioteca.GUI;

import com.mycompany.sistemaBiblioteca.Logica.Socio;
import com.mycompany.sistemaBiblioteca.Logica.Libro;
/**
 *
 * @author saave
 *
 *
 */
public class FrmPrestamo extends javax.swing.JInternalFrame implements com.mycompany.sistemaBiblioteca.Logica.PrestamoObserver {

    /**
     * Creates new form FrmPrestamo
     */
    public FrmPrestamo() {
        initComponents();
        // Registrar este frame como observador
        com.mycompany.sistemaBiblioteca.Logica.BibliotecaFacade.getInstancia().agregarObservador(this);

        // Setear fechas por defecto
        txtFechaPrestamo.setText(dateFormat.format(new java.util.Date()));
        txtFechaRealDev.setText(dateFormat.format(new java.util.Date()));

        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.add(java.util.Calendar.DAY_OF_YEAR, 7);
        txtFechaPrevista.setText(dateFormat.format(cal.getTime()));

        actualizarCombosYTablas();
    }

    private final java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrarPrestamo = new javax.swing.JButton();
        cbSocio = new javax.swing.JComboBox<>();
        cbLibro = new javax.swing.JComboBox<>();
        txtFechaPrestamo = new javax.swing.JTextField();
        txtFechaPrevista = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamosActivos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdPrestamoDev = new javax.swing.JTextField();
        txtSocioDev = new javax.swing.JTextField();
        txtLibroDev = new javax.swing.JTextField();
        txtFechaPrevistaDev = new javax.swing.JTextField();
        txtFechaRealDev = new javax.swing.JTextField();
        txtMultaDev = new javax.swing.JTextField();
        btnCalcularMulta = new javax.swing.JButton();
        btnRegistrarDevolucion = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar nuevo prestamo"));

        jLabel1.setText("Seleccione Socio");

        jLabel2.setText("Seleccione Libro");

        jLabel3.setText("Fecha Prestamos");

        jLabel4.setText("Fecha Dev.Prevista");

        btnRegistrarPrestamo.setText("Registrar Prestamo");
        btnRegistrarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPrestamoActionPerformed(evt);
            }
        });

        txtFechaPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(txtFechaPrevista))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnRegistrarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cbSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnRegistrarPrestamo)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Prestamos Activos"));

        tblPrestamosActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Prestamo", "Socio", "Libro", "F.Prevista"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrestamosActivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPrestamosActivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPrestamosActivos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Devolucion"));

        jLabel5.setText("ID Prestamo");

        jLabel6.setText("Socio");

        jLabel7.setText("Libro");

        jLabel8.setText("F.Prevista");

        jLabel9.setText("F.Real Devolucion");

        jLabel10.setText("Multa Calculada");

        btnCalcularMulta.setText("Calcular Multa");
        btnCalcularMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularMultaActionPerformed(evt);
            }
        });

        btnRegistrarDevolucion.setText("Confirmar Devolucion");
        btnRegistrarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDevolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdPrestamoDev, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(txtSocioDev)
                            .addComponent(txtLibroDev)
                            .addComponent(txtFechaPrevistaDev)
                            .addComponent(txtFechaRealDev)
                            .addComponent(txtMultaDev))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCalcularMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(btnRegistrarDevolucion)
                        .addGap(62, 62, 62))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdPrestamoDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSocioDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtLibroDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtFechaPrevistaDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtFechaRealDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtMultaDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarDevolucion)
                    .addComponent(btnCalcularMulta))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPrestamoActionPerformed
        com.mycompany.sistemaBiblioteca.Logica.Socio s = (com.mycompany.sistemaBiblioteca.Logica.Socio) cbSocio.getSelectedItem();
        com.mycompany.sistemaBiblioteca.Logica.Libro l = (com.mycompany.sistemaBiblioteca.Logica.Libro) cbLibro.getSelectedItem();
        if (s == null || l == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar Socio y Libro.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            java.util.Date fPrestamo = dateFormat.parse(txtFechaPrestamo.getText().trim());
            java.util.Date fPrevista = dateFormat.parse(txtFechaPrevista.getText().trim());
            if (fPrevista.before(fPrestamo)) {
                javax.swing.JOptionPane.showMessageDialog(this, "La fecha de devolución no puede ser anterior al préstamo.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            com.mycompany.sistemaBiblioteca.Logica.Prestamo p = new com.mycompany.sistemaBiblioteca.Logica.Prestamo();
            p.setSocio(s);
            p.setLibro(l);
            p.setFechaPrestamo(fPrestamo);
            p.setFechaDevolucionPrevista(fPrevista);
            com.mycompany.sistemaBiblioteca.Logica.BibliotecaFacade.getInstancia().registrarPrestamo(p);
            javax.swing.JOptionPane.showMessageDialog(this, "¡Préstamo registrado con éxito!", "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            // El Observer actualizará el stock e inventarios automáticamente
        } catch (java.text.ParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Fecha inválida. Use AAAA-MM-DD.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IllegalStateException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Negocio", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarPrestamoActionPerformed

    private void btnCalcularMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularMultaActionPerformed
        if (txtIdPrestamoDev.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un préstamo de la lista.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            java.util.Date prevista = dateFormat.parse(txtFechaPrevistaDev.getText());
            java.util.Date real = dateFormat.parse(txtFechaRealDev.getText().trim());
            double multa = com.mycompany.sistemaBiblioteca.Logica.BibliotecaFacade.getInstancia().calcularMulta(prevista, real);
            txtMultaDev.setText("$" + multa);
        } catch (java.text.ParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Fecha real inválida.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularMultaActionPerformed

    private void btnRegistrarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDevolucionActionPerformed
        if (txtIdPrestamoDev.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un préstamo de la lista.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            Integer id = Integer.parseInt(txtIdPrestamoDev.getText());
            java.util.Date real = dateFormat.parse(txtFechaRealDev.getText().trim());
            java.util.Date prevista = dateFormat.parse(txtFechaPrevistaDev.getText());

            double multa = com.mycompany.sistemaBiblioteca.Logica.BibliotecaFacade.getInstancia().calcularMulta(prevista, real);
            com.mycompany.sistemaBiblioteca.Logica.BibliotecaFacade.getInstancia().registrarDevolucion(id, real);
            String msj = "Devolución completada.";
            if (multa > 0) {
                msj += "\nMulta generada: $" + multa;
            }

            javax.swing.JOptionPane.showMessageDialog(this, msj, "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposDevolucion();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarDevolucionActionPerformed

    private void tblPrestamosActivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrestamosActivosMouseClicked
        cargarPrestamoSeleccionado();
    }//GEN-LAST:event_tblPrestamosActivosMouseClicked

    private void txtFechaPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaPrestamoActionPerformed

    private void actualizarCombosYTablas() {
        // 1. Cargar Socios activos
        cbSocio.removeAllItems();
        java.util.ArrayList<com.mycompany.sistemaBiblioteca.Logica.Socio> socios
                = com.mycompany.sistemaBiblioteca.Logica.BibliotecaFacade.getInstancia().listarSocios();
        for (com.mycompany.sistemaBiblioteca.Logica.Socio s : socios) {
            if ("Activo".equalsIgnoreCase(s.getEstado())) {
                cbSocio.addItem(s);
            }
        }

        // 2. Cargar Libros disponibles
        cbLibro.removeAllItems();
        java.util.ArrayList<com.mycompany.sistemaBiblioteca.Logica.Libro> libros
                = com.mycompany.sistemaBiblioteca.Logica.BibliotecaFacade.getInstancia().listarLibrosDisponibles();
        for (com.mycompany.sistemaBiblioteca.Logica.Libro l : libros) {
            cbLibro.addItem(l);
        }

        // 3. Cargar Tabla de Préstamos Activos
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPrestamosActivos.getModel();
        model.setRowCount(0);
        java.util.ArrayList<com.mycompany.sistemaBiblioteca.Logica.Prestamo> activos
                = com.mycompany.sistemaBiblioteca.Logica.BibliotecaFacade.getInstancia().listarPrestamosActivos();
        for (com.mycompany.sistemaBiblioteca.Logica.Prestamo p : activos) {
            Object[] fila = {
                p.getIdPrestamo(),
                p.getSocio().getNombreCompleto(),
                p.getLibro().getTitulo(),
                dateFormat.format(p.getFechaDevolucionPrevista())
            };
            model.addRow(fila);
        }
    }

    private void cargarPrestamoSeleccionado() {
        int fila = tblPrestamosActivos.getSelectedRow();
        if (fila != -1) {
            txtIdPrestamoDev.setText(tblPrestamosActivos.getValueAt(fila, 0).toString());
            txtSocioDev.setText(tblPrestamosActivos.getValueAt(fila, 1).toString());
            txtLibroDev.setText(tblPrestamosActivos.getValueAt(fila, 2).toString());
            txtFechaPrevistaDev.setText(tblPrestamosActivos.getValueAt(fila, 3).toString());
            txtFechaRealDev.setText(dateFormat.format(new java.util.Date()));
            txtMultaDev.setText("$0.0");
        }
    }

    private void limpiarCamposDevolucion() {
        txtIdPrestamoDev.setText("");
        txtSocioDev.setText("");
        txtLibroDev.setText("");
        txtFechaPrevistaDev.setText("");
        txtFechaRealDev.setText(dateFormat.format(new java.util.Date()));
        txtMultaDev.setText("$0.0");
        tblPrestamosActivos.clearSelection();
    }

    // Métodos de la Interfaz PrestamoObserver
    @Override
    public void onPrestamoRegistrado(com.mycompany.sistemaBiblioteca.Logica.Prestamo p) {
        actualizarCombosYTablas();
    }

    @Override
    public void onPrestamoDevuelto(com.mycompany.sistemaBiblioteca.Logica.Prestamo p) {
        actualizarCombosYTablas();
    }

    @Override
    public void dispose() {
        // Desuscribirse al cerrar el frame
        com.mycompany.sistemaBiblioteca.Logica.BibliotecaFacade.getInstancia().removerObservador(this);
        super.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularMulta;
    private javax.swing.JButton btnRegistrarDevolucion;
    private javax.swing.JButton btnRegistrarPrestamo;
    private javax.swing.JComboBox<Libro> cbLibro;
    private javax.swing.JComboBox<Socio> cbSocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrestamosActivos;
    private javax.swing.JTextField txtFechaPrestamo;
    private javax.swing.JTextField txtFechaPrevista;
    private javax.swing.JTextField txtFechaPrevistaDev;
    private javax.swing.JTextField txtFechaRealDev;
    private javax.swing.JTextField txtIdPrestamoDev;
    private javax.swing.JTextField txtLibroDev;
    private javax.swing.JTextField txtMultaDev;
    private javax.swing.JTextField txtSocioDev;
    // End of variables declaration//GEN-END:variables
}
