/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.sistemabiblioteca.GUI;

/**
 *
 * @author saave
 */
public class Principal extends javax.swing.JFrame {
        // Instancias de las ventanas internas para evitar duplicados
    private FrmSocio frmSocio;
    private FrmAutor frmAutor;
    private FrmCategoria frmCategoria;
    private FrmLibro frmLibro;
    private FrmPrestamo frmPrestamo;
    private FrmBusquedaLibro frmBusquedaLibro;
    private FrmHistorialSocio frmHistorialSocio;
    
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
            // Configurar Look & Feel Nimbus y título
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    setTitle("Sistema de Biblioteca - Patrones GOF");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        iteamSocios = new javax.swing.JMenuItem();
        iteamAutores = new javax.swing.JMenuItem();
        iteamCategorias = new javax.swing.JMenuItem();
        iteamLibros = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        iteamPrestamos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        iteamBusqueda = new javax.swing.JMenuItem();
        iteamHistorial = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Gestion");

        iteamSocios.setText("Socios");
        iteamSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteamSociosActionPerformed(evt);
            }
        });
        jMenu2.add(iteamSocios);

        iteamAutores.setText("Autores");
        iteamAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteamAutoresActionPerformed(evt);
            }
        });
        jMenu2.add(iteamAutores);

        iteamCategorias.setText("Categorias");
        iteamCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteamCategoriasActionPerformed(evt);
            }
        });
        jMenu2.add(iteamCategorias);

        iteamLibros.setText("Libros");
        iteamLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteamLibrosActionPerformed(evt);
            }
        });
        jMenu2.add(iteamLibros);

        menuBar.add(jMenu2);

        jMenu3.setText("Operaciones");

        iteamPrestamos.setText("Prestamo y Devoluciones");
        iteamPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteamPrestamosActionPerformed(evt);
            }
        });
        jMenu3.add(iteamPrestamos);

        menuBar.add(jMenu3);

        jMenu4.setText("Consultas");

        iteamBusqueda.setText("Busqueda avanzada de libros");
        iteamBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteamBusquedaActionPerformed(evt);
            }
        });
        jMenu4.add(iteamBusqueda);

        iteamHistorial.setText("Historial Prestamo por Socio");
        iteamHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteamHistorialActionPerformed(evt);
            }
        });
        jMenu4.add(iteamHistorial);

        menuBar.add(jMenu4);

        jMenu5.setText("Archivo");

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        jMenu5.add(itemSalir);

        menuBar.add(jMenu5);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iteamSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteamSociosActionPerformed
       if (frmSocio == null || frmSocio.isClosed()) {
            frmSocio = new FrmSocio();
            desktopPane.add(frmSocio);
        }
        mostrarFrameInterno(frmSocio);
    }//GEN-LAST:event_iteamSociosActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void iteamAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteamAutoresActionPerformed
        if (frmAutor == null || frmAutor.isClosed()) {
            frmAutor = new FrmAutor();
            desktopPane.add(frmAutor);
        }
        mostrarFrameInterno(frmAutor);
    }//GEN-LAST:event_iteamAutoresActionPerformed

    private void iteamCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteamCategoriasActionPerformed
    if (frmCategoria == null || frmCategoria.isClosed()) {
            frmCategoria = new FrmCategoria();
            desktopPane.add(frmCategoria);
        }
        mostrarFrameInterno(frmCategoria);
    }//GEN-LAST:event_iteamCategoriasActionPerformed

    private void iteamLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteamLibrosActionPerformed
    if (frmLibro == null || frmLibro.isClosed()) {
            frmLibro = new FrmLibro();
            desktopPane.add(frmLibro);
        }
        mostrarFrameInterno(frmLibro);
    }//GEN-LAST:event_iteamLibrosActionPerformed

    private void iteamPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteamPrestamosActionPerformed
        if (frmPrestamo == null || frmPrestamo.isClosed()) {
            frmPrestamo = new FrmPrestamo();
            desktopPane.add(frmPrestamo);
        }
        mostrarFrameInterno(frmPrestamo);
    }//GEN-LAST:event_iteamPrestamosActionPerformed

    private void iteamBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteamBusquedaActionPerformed
        if (frmBusquedaLibro == null || frmBusquedaLibro.isClosed()) {
            frmBusquedaLibro = new FrmBusquedaLibro();
            desktopPane.add(frmBusquedaLibro);
        }
        mostrarFrameInterno(frmBusquedaLibro);
    }//GEN-LAST:event_iteamBusquedaActionPerformed

    private void iteamHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteamHistorialActionPerformed
       if (frmHistorialSocio == null || frmHistorialSocio.isClosed()) {
            frmHistorialSocio = new FrmHistorialSocio();
            desktopPane.add(frmHistorialSocio);
        }
        mostrarFrameInterno(frmHistorialSocio);
    }//GEN-LAST:event_iteamHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    
        private void mostrarFrameInterno(javax.swing.JInternalFrame iframe) {
        try {
            iframe.setVisible(true);
            iframe.setSelected(true);
            iframe.toFront();
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem iteamAutores;
    private javax.swing.JMenuItem iteamBusqueda;
    private javax.swing.JMenuItem iteamCategorias;
    private javax.swing.JMenuItem iteamHistorial;
    private javax.swing.JMenuItem iteamLibros;
    private javax.swing.JMenuItem iteamPrestamos;
    private javax.swing.JMenuItem iteamSocios;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
